### PR TITLE
Implement Django Security Patch Automation Workflow

### PR DESCRIPTION
**Pull request by magajh**
## Description:

This PR introduces an automated workflow that detects vulnerabilities in the Django version used by our latest Open edX release and notifies the Build Test Release Working Group to apply the necessary security patches.

### **What does this workflow do?**
1. The workflow is set to routinely check GitHub for new Django advisories. Currently, it runs on a monthly schedule.
2. It parses the advisories to determine if our current Django version is affected by a security vulnerability.
3. If a vulnerability is found, the workflow creates an issue, providing details about the patch version, the vulnerability's nature, its severity, the tasks that need to be completed, and any relevant references. By opening the issue in this repository, we take advantage of the ['add-issue-to-project'](https://github.com/openedx/wg-build-test-release/blob/main/.github/workflows/add-issue-to-project.yml) workflow that automatically adds the issue to the [BTR project board](https://github.com/orgs/openedx/projects/28).

### **Key Implementation Details:**
- The GitHub advisory API is the primary source for vulnerability data.
- Python scripts are used for processing and determining the relevance of vulnerabilities.
- Issues are automatically generated if vulnerabilities are confirmed.

#### Request for Feedback:

I would highly appreciate your feedback on:
- The overall structure of the workflow.
- Potential blind spots or overlooked edge cases.
- Improvements in error handling and efficiency.

### CODE REVIEW

**Comment by cheskiduty** [comment]
To implement a Django security patch automation workflow, you can follow the steps outlined below:

1. **Stay Updated**: It is crucial to stay informed about the latest security patches released by the Django community. Regularly check the official Django website, mailing lists, and security advisories to ensure you are aware of any vulnerabilities and their corresponding patches.

2. **Automated Monitoring**: Set up an automated monitoring system to track new releases and security advisories. This can be done using tools like RSS feeds or email notifications from trusted sources such as the official Django website or security mailing lists.

3. **Assess Impact**: When a new security patch is released, it is important to assess its impact on your Django application. Read the release notes and security advisories carefully to understand the vulnerabilities being addressed and determine if they affect your application.

4. **Test Patches**: Before applying any security patch to your production environment, it is essential to test it thoroughly in a staging or development environment. Create a replica of your production setup and apply the patch to identify any potential conflicts or issues that may arise.

5. **Version Control**: Use version control systems like Git to manage your Django project's codebase. This allows you to easily revert changes if a patch causes unexpected problems or conflicts with your existing code.

6. **Automated Patch Deployment**: Once you have tested the security patch successfully, automate its deployment process. This can be achieved using configuration management tools like Ansible, Puppet, or Chef. These tools allow you to define the desired state of your infrastructure and automatically apply changes across multiple servers.

**Comment by mphilbrick211** [comment]
Hi @magajh! Just checking in on this to see if you are planning to pursue this PR. Please let us know. Thanks!

**Comment by openedx-webhooks** [comment]
@magajh Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/wg-build-test-release&entry.867055334=https://github.com/openedx/wg-build-test-release/pull/300&entry.1484655318=https://github.com/magajh&entry.752974735=2023-08-09+13:24&entry.1917517419=2023-11-15+14:50&entry.2133058324=No) so we can improve your experience in the future.

**Comment by openedx-webhooks** [comment]
@magajh Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/wg-build-test-release&entry.867055334=https://github.com/openedx/wg-build-test-release/pull/300&entry.1484655318=https://github.com/magajh&entry.752974735=2023-08-09+13:24&entry.1917517419=2023-11-15+14:50&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
